### ISSUE TITLE
typeof cache.get_proxy(request.connection.id) !== 'undefined' is invalid

### ISSUE THREAD

**Issue by todddcls** [einfallstoll/express-ntlm#15]
cache.get returns null, typeof null = object not undefined.  Should just be checking cache.get_proxy(request.connection.id) != null, or make cache.get return undefined instead of null.

**Comment by einfallstoll** [comment]
I belive it'd be also possible to just use `if (cache.get_proxy(request.connection.id)) { ... }` to handle both `undefined` and `null`.
