### ISSUE TITLE
Express-ntlm and CORS: Chrome keeps getting 401 Unauthorized responses

### ISSUE THREAD

**Issue by yipiha** [einfallstoll/express-ntlm#16]
Hi,

I am trying to use express-ntlm to retrieve the username only (authentication is not required) from an angular application.

It works well on IE 11 but on Chrome and Firefox, the request never succeed and keep getting 401 responses. Is there something wrong in my code or is it an issue with express-ntlm? Thanks in advance.

=> Node server.js file
// list of plugin includes
var http = require('http');
var express = require('express');
var ntlm = require('express-ntlm');
var bodyParser = require('body-parser')
var logger = require('./logging.js');

// list of custom modules
var controllers = require('./controllers');

// define application port
var port = process.env.port || 1337;

// create express' singleton
var app = express();

// Add parsers
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

// add express-ntlm
app.use(ntlm());

// start the controllers
controllers.start(app);

// define express as our main application on the server
// start the server that starts litening on defined port
http.createServer(app).listen(port);

// define allowed routes for CORS
app.all('/*', function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Credentials", "true");
    res.header("Access-Control-Allow-Headers", "X-Requested-With,Content-Type, Accept");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    next();
});

// Identify users
app.use('/admin/user', function (request, response) {
        response.json(request.ntlm.UserName); 
});

=> Angular configuration (for information purpose)
App.config(function ($httpProvider) {
            $httpProvider.defaults.useXDomain = true;
            delete $httpProvider.defaults.headers.common['X-Requested-With'];
        });

**Comment by einfallstoll** [comment]
CORS has nothing to do with the 401 responses you get. Those responses mean "Authentication Required" and most likely have some header information requesting an NTLM-authentication. So far everything seems working as expected.

It's known that Firefox does not support NTLM and Chrome may have disabled it in some release.

Retrieving the username without some real authentication is not recommended, since it can't be validated.

I suggest you to configure an active directory with NTLM enabled or use some other authentication method.

**Comment by yipiha** [comment]
I see - thanks for your quick feedback. 

I thought it was CORS related because if I remove the following part, the "// define allowed routes for CORS" then the "// Identify users" part is never hit.

So if I understand correctly I should forget about CORS here and focus on trying with another version of chrome. The application is within the intranet and there is an active directory - getting the username is just to log who did what using the application, not a security concern. Maybe I am going the wrong direction but I thought it would be easier using express-ntlm than creating a proxy page using some C# to get the currently connected user and his name.

I started using express-ntlm a an easy way to identify users as per this thread:
http://stackoverflow.com/questions/27631126/how-to-get-current-windows-user-from-express

Thanks again.

**Comment by einfallstoll** [comment]
The NTLM-middleware does some amazing stuff for you and handles multiple requests for you without even letting an unauthenticated request in. So, as long as the request isn't authenticated your CORS-middleware will never be called.

My module is definitely some easy way for this to do, but as said: Firefox doesn't fully support NTLM so it's not possible to log the username without having them to log in. And as soon as they see the default authentication form, they'd be able to write whatever they want and if you don't validate it against an active directory they'll be able to fake their usernames.

**Comment by einfallstoll** [comment]
If you'd have to use a C# proxy page I'd recommend you to add the active directory to authenticate to. It's really easy designed, because I'm lazy as fuck and don't want to make a huge setup for a simple authentication.

**Comment by yipiha** [comment]
Thanks a lot for sharing your knowledge and your precious advices.
