### ISSUE TITLE
not to return response.sendStatus 400, 403 and 500

### ISSUE THREAD

**Issue by daneshka** [einfallstoll/express-ntlm#19]
Sorry if I'm wrong !
I want to show specific UI if the user/pass is incorrect. 
I couldn't find any way to handle errors because in the code it return response.sendStatus and I don't have access to it anymore.
we can set status and call next so it could be handled.
Thanks

**Comment by einfallstoll** [comment]
You can set them via the options:

````
app.use(ntlm({
    badrequest: function(request, response, next) {
        // custom implementation
    }
}));
````

See the README for further information.
