### ISSUE TITLE
Question: Is there a way to log out?

### ISSUE THREAD

**Issue by stefanheine** [einfallstoll/express-ntlm#21]
Hi,

the NTLM authentication is working pretty good now, even behind nginx (and I'll send proper documentation once I'm really satisfied), but for testing (and also users might have that request), I'd like to know if there is a way to log out? some way to drop an existing authentication session between client/browser and server? that forces a new authentication on the next request?
I can work around by making the browser forget the history (including active logins), but I have seen situations (eg. after a password change), where the browser had cached outdated information and did not properly re-establish the session, resulting in a '403/ Forbidden' coming back.

Regards
  Stefan

**Comment by einfallstoll** [comment]
I don't think NTLM is designed to be able to get logged out. But you should be able to achieve this very easily by deleting my connection id.

````
app.get('/logout', function(request, response) {
    delete request.connection.id;
    // redirect to the last site?
});
````
