### ISSUE TITLE
Add support for custom port number in domaincontroller URL

### ISSUE THREAD

**Issue by gshklover** [einfallstoll/express-ntlm#23]
Please provide support for custom port number in domaincontroller URL.
Example URL: 'ldap://my.corp.com:3233'
Requires a slight change to the way decoded URL is passed into "new NTLM_AD_Proxy()" in express-ntlm.js:111-114

**Comment by gshklover** [comment]
Thanks!

**Comment by einfallstoll** [comment]
No problems, let me know if it doesn't work.

**Comment by gshklover** [comment]
Hi.

There is a problem with the fix: the URL is parsed twice (once outside the proxy constructor, and the other time inside the constructor).
So: ldap://smth.com:XYZ is first parsed and then url.domain is passed into Proxy constractor.
(url.domain = smth.com:XYZ)

Then url.parse() is called again, now the parsing ends up like this:
protocol = smth.com
domain: XYZ
port = null

**Comment by gshklover** [comment]
Hi. Is there an update on this issue?

Thanks.

**Comment by gshklover** [comment]
Hi. Thanks for response.
The issue is still not resolved though: express-ntlm.js line 114 should use 'serverurl.hostname' instead of 'serverurl.host'.

Thanks,
Gregory.
