### ISSUE TITLE
"No Authorization header present" with Chrome

### ISSUE THREAD

**Issue by oxodesign** [einfallstoll/express-ntlm#37]
Im doing a test on my local env. and its working when testing it with IE and Postman. But the authentication is not working with Chrome.

Did a lot of searching and tried different solutions but non of them seems to work

Here its what I have done:
https://gist.github.com/mlynch/be92735ce4c547bd45f6
https://specopssoft.com/configuring-chrome-and-firefox-for-windows-integrated-authentication

Does anyone have any suggestion how to fix this.?

**Comment by einfallstoll** [comment]
I can't remember configuring something specific for Google Chrome to work with NTLM. Also it seems like [NTLM is enabled by default](https://www.chromium.org/developers/design-documents/http-authentication).

**Comment by oxodesign** [comment]
@einfallstoll hmmm no havent used Wireshark, downloading it now, what should I look for?

**Comment by einfallstoll** [comment]
It's going to show you **all** packets on your interface – and that'll be a lot. Look for the specific requests to your application and look wether your browser handles the responds correctly... It'll take some time to understand everything, but it's worth the effort – for this issue and for others you might encounter in the future.
It's also possible to save the dump and and send it to me – but I might be a bad person 😁

**Comment by einfallstoll** [comment]
Any update on this? If not I will close the issue.

**Comment by oxodesign** [comment]
No, but havent had much time to investigate. Tried to use Wireshark but could not figure out what really happens.

We dropped SSO and started using JWT.
