### ISSUE TITLE
Authentication was broken in last version

### ISSUE THREAD

**Issue by hkeeper** [einfallstoll/express-ntlm#38]
Users sent us reports, that now they can use any password and any userName in the FireFox NTLM login window.
Indeed first time they got an error, but after several F5 press - they can use applications under other users accounts.
 The reason was new 2.2.2 version.
In the previous(2.1.5) was the code:
 if (!result) {
                cache.remove(request.connection.id);
                options.debug(options.prefix, 'User ' + domain + '/' + user + ' authentication for URI ' + request.protocol + '://' + request.get('host') + request.originalUrl);
                return options.forbidden(request, response, next);
            } else {
                request.ntlm = userData;
                response.locals.ntlm = userData;
                request.connection.ntlm = userData;
So in the case of unauthorized request, cache removes id of connection and returns _before_ save userData to request.connection.

In the latest(2.2.2) version, logic was broken and userData is saved to connection _before_ return
           request.connection.ntlm = userData;

            if (!result) {
                cache.remove(request.connection.id);
                options.debug(options.prefix, 'User ' + domain + '/' + user + ' authentication for URI ' + request.protocol + '://' + request.get('host') + request.originalUrl);
                return options.forbidden(request, response, next);

So during next requests, request.connection will contain userData and check againtst AD won't be done.

**Comment by einfallstoll** [comment]
Could you test it against this test ranch?

    npm install github:einfallstoll/express-ntlm#add-authenticated-field --save

**Comment by hkeeper** [comment]
Can do it later, but according your commit, looks that it should work properly

**Comment by einfallstoll** [comment]
> If it's not tested, it's broken.

☺️

**Comment by einfallstoll** [comment]
@hkeeper Any update on this?

**Comment by houldsg** [comment]
I just tested with invalid credentials and can confirm it's broken and allows you to log in as anyone.
I'll test with the add-authenticated-field branch and report back shortly.

**Comment by houldsg** [comment]
@einfallstoll Yes. The changes in commit 1cf70885ec1096a8ce48444376b192b8cdd6fd64 resolve the issue for me. Invalid credentials are rejected consistently across multiple requests.
