### ISSUE TITLE
 Mixing-up through sessions

### ISSUE THREAD

**Issue by danielriosb** [einfallstoll/express-ntlm#40]
Hi, I have a web app that starts having some issue with users authentication. Sometimes, my users are logged in as another user. So there seems to be some mixing-up through sessions.

I will appreciate your help with this. Thanks

**Comment by einfallstoll** [comment]
Do you use a reverse proxy in front of the application?

**Comment by danielriosb** [comment]
I use IIS which  have a proxy tho other than that no I don't use any proxy.

**Comment by einfallstoll** [comment]
What's the purpose of your IIS? I need to understand the environment to help you out.

**Comment by danielriosb** [comment]
Ok. I am using IIS to run on a windows server box a MEAN Stack app.

**Comment by einfallstoll** [comment]
So all traffic to your node app goes through the IIS?

**Comment by danielriosb** [comment]
Yes. Everything. When 2 or more users log in at the same time is when I get the issue.

**Comment by einfallstoll** [comment]
If your traffic goes through IIS, this **is** a [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) – and this is not supported by NTLM. Either don't use IIS and connect directly to the node application or try to implement NTLM on IIS itself, that should be possible somehow, but I'm not sure.
