### ISSUE TITLE
Retry failed authentication?

### ISSUE THREAD

**Issue by stefanheine** [einfallstoll/express-ntlm#42]
Hi,

I'm using express-ntlm succesfully in my app. When I point my browser to the app url, it opens the username/password dialog, I can enter it and it authenticates or fails.

but if I mistype the password, and it fails (returns 'Forbidden'), how can I go back to get the username/password dialog again? because currently, obviously the browser is caching some credentials, even though they failed. so every time I reopen by app url, it immediately fails.

the current workaround is to clean the browser cache/ cookies to make the dialog come up again, but that's not very nice for those users needing two or three attempts to correctly type the password.

Regards
  Stefan

**Comment by einfallstoll** [comment]
Hi Stefan,

I guess the browser has to save the credentials when receiving a 403. Usually this is good, because the browser should use NTLM instead of a "NTLM-over-basic-authentication". 
You could probably get around this by overwriting the `forbidden` function in the options with a simple redirect and maybe a 401 status code.

- Fabio

**Comment by stefanheine** [comment]
thanks. this code is giving me what I want: a redirect to the same url, until the authentication finally succeeds:

```
  forbidden(req, res) {
      res
      .status(401)
      .send(`<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=${req.url}">
    }
```

**Comment by einfallstoll** [comment]
You should also be able to set the `Location` header by using `res.redirect(url)` which doesn't require the HTML-refresh

**Comment by stefanheine** [comment]
nope...
```
    forbidden(req, res) {
      res
      .status(401)
      .location(req.url).end();
    }
```
just ends with a blank page, but no redirect.

**Comment by einfallstoll** [comment]
Of course... if you're sending a 401 it won't redirect, but if you don't it will save / cache the credentials. Your HTML-solution is kinda ugly, but probably the only way to achieve both.

**Comment by stefanheine** [comment]
yes... that's why I need it so ugly... I'll happily switch to anything nicer, provided it works ;)

**Comment by zaxy78** [comment]
works for me too. Thanks !

**Comment by danielriosb** [comment]
works for me as well but anyway to show a message saying "Wrong password!" when prompting for username and password again? Thanks

**Comment by einfallstoll** [comment]
An ugly way would be to delay the redirect on the HTML Redirect page (as seen above).

If you want a fancier implementation your users should use IE (don't say anyone I told you so) which implements NTLM properly or make your custom implementation using a username + password field. It should even be possible to fallback to a simple form if NTLM failed.

**Comment by danielriosb** [comment]
> thanks. this code is giving me what I want: a redirect to the same url, until the authentication finally succeeds:
> 
> ```
>   forbidden(req, res) {
>       res
>       .status(401)
>       .send(`<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=${req.url}">
>     }
> ```

looks like HTML-refresh is not working for Safari, I'm trying with js,but no success yet.
`<script type="text/javascript">   
    function Redirect() 
        {  
            window.location="urlScheme://"; 
        } 
        setTimeout('Redirect()', 1000);   
</script>`
