### ISSUE TITLE
ETIMEDOUT errors intermittently

### ISSUE THREAD

**Issue by lukewendling** [einfallstoll/express-ntlm#46]
For some users, and not all the time, the app throws **ETIMEDOUT** errors, which are logged in the `debug` handler in ntlm. I'm wondering if this is to do with proxying... We don't have nginx or any web server in front of the app processes... however, we do use a pm2-like process manager, called strongloop PM. It forwards requests to a Node cluster. Can this cause intermittent failures?

**Comment by einfallstoll** [comment]
Yes, proxies are not supported by NTLM by design because it authenticates connections not "sessions".

**Comment by einfallstoll** [comment]
I have to append: It's only a problem if the connections won't be keeped alive or distributed across multiple servers.

**Comment by lukewendling** [comment]
Thanks @einfallstoll - Do you have a recommendation on how to support process managers like pm2 or do we need to run a single node process for express-ntlm to work correctly?

**Comment by einfallstoll** [comment]
Sorry, for the late response. An ideal solution would probably be a single node process for NTLM to work correctly (I have to note, that this is not an issue of `express-ntlm` itself, but an issue of NTLM in general). Although it should work with every proxy if you can make sure, that connections end at the same node.

I also digged a little bit in `strong-pm` and it seems like that this is not possible. [See this issue](https://github.com/strongloop/strong-pm/issues/97).
