### ISSUE TITLE
Call windows authenticated web api from nodejs client

### ISSUE THREAD

**Issue by BilgehanYildiz** [einfallstoll/express-ntlm#48]
Can I use it to call windows authenticated web api to pass credential ?

**Comment by einfallstoll** [comment]
No. This module acts as the NTLM-Server, not the Client.

**Comment by BilgehanYildiz** [comment]
Can you advise any package or method from my case?

**Comment by einfallstoll** [comment]
I have no experience in authenticating against NTLM rather than providing NTLM itself, therefore I lack the knowledge to provide an answer. Sorry.

**Comment by BilgehanYildiz** [comment]
Thank you
