### ISSUE TITLE
Intermittently receiving 401 errors from express-ntlm

### ISSUE THREAD

**Issue by FortressDave** [einfallstoll/express-ntlm#50]
Hello,

I have several NodeJS applications hosted on one windows server.  Those applications are accessed via a NodeJS based proxy server (using the http-proxy module).  I need only user names in the applications to identify the users connecting so express-ntlm is installed in the proxy which then passes the user name along to the applications in a custom header.

This works very well most of the time, however, occasionally the proxy returns 401 responses which force the authentication popup to open in Chrome.  I see through fiddler that this sometimes happens after the client sends the final challenge request and receives the 401 instead of the expected 200. 

I am at a loss trying to figure out what is going on or how to resolve it.  Based on the above set up are there any known issues I could be running into?  I read the disclaimer about running through a proxy but in my case express-ntlm is running at the proxy level so the client is connecting directly to the layer running express-ntlm.  I thought this would be a valid workaround and does work most of the time.  

Thanks

**Comment by einfallstoll** [comment]
Hard to tell without the logs from `express-ntlm`. Could you implement a debug-function and pass it to the module? Like the one in the [example](https://github.com/einfallstoll/express-ntlm#example-usage).

**Comment by FortressDave** [comment]
Thanks for the response, I do have the logging turned on.  When this event happens I see only this in the logs (replaced the client domain with "CLIENTDOMAIN"):

[express-ntlm] No Authorization header present
[express-ntlm] Initiating connection to Active Directory server ldap.clientdomain.com (domain CLIENTDOMAIN) using base DN "null".

Here is the set up in the code:

app.use(ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    domain: 'CLIENTDOMAIN',
    domaincontroller: 'ldap://ldap.clientdomain.com',
}));

I don't think it is a connectivity problem with the Ldap server, I noticed that if I cannot connect to the domain we'll get a 500.  Is there a way to add additional logging to see what might be going on when the 401 is returned?

**Comment by FortressDave** [comment]
I discovered a little more info here.  I can get this authentication handshake/challenge to fails by opening the site and allowing the browser to sit open for some time.  Then I perform a post from the browser javascript(AJAX).  The final 401 contains the following error:

TypeError: Cannot read property &#39;authenticate&#39; of null<br> &nbsp; &nbsp;at handle_type3 (D:\NodeJS\Proxy\node_modules\express-ntlm\lib\express-ntlm.js:169:14)<br> &nbsp; &nbsp;at D:\NodeJS\Proxy\node_modules\express-ntlm\lib\express-ntlm.js:245:24<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NodeJS\Proxy\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (D:\NodeJS\Proxy\node_modules\express\lib\router\index.js:312:13)<br> &nbsp; &nbsp;at D:\NodeJS\Proxy\node_modules\express\lib\router\index.js:280:7<br> &nbsp; &nbsp;at Function.process_params (D:\NodeJS\Proxy\node_modules\express\lib\router\index.js:330:12)<br> &nbsp; &nbsp;at next (D:\NodeJS\Proxy\node_modules\express\lib\router\index.js:271:10)<br> &nbsp; &nbsp;at expressInit (D:\NodeJS\Proxy\node_modules\express\lib\middleware\init.js:33:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NodeJS\Proxy\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (D:\NodeJS\Proxy\node_modules\express\lib\router\index.js:312:13)
