### ISSUE TITLE
login any users

### ISSUE THREAD

**Issue by joker63** [einfallstoll/express-ntlm#51]
Hi. If use basic authorization in URL (http://login:password@localhost)
http://aetp%5crylkov.i:trololo123@localhost:3200
(any login active directory) aetp%5csentyrin.a = aetp/sentyrin.a
(password)trololo123 = is not correct password to aetp/sentyrin.a

The request will pass successfully and return (login aetp/sentyrin.a).
The result will be the same on any page, until you restart the browser
Reproduced in Google Chrome

**Comment by einfallstoll** [comment]
Please show include a code example of your implementation.

**Comment by joker63** [comment]
code from your example
`var express = require('express');
var app = express();
var server = require('http').createServer(app);
var ntlm = require('express-ntlm');

app.use(ntlm());

app.use(function(req, res, next) {
  res.json(req.ntlm.UserName);
});

var port = process.env.PORT || 3200;
server.listen(port, function() {
  console.log(
    'Express server listening on port %d in %s mode',
    port,
    app.get('env')
  );
});
`

**Comment by einfallstoll** [comment]
Not providing options to `ntlm()` disables proper authentication. So this is expected behaviour. Please provide an options object and specify at least a domain controller.
