### ISSUE TITLE
Chrome forces users to enter username/password manually

### ISSUE THREAD

**Issue by cazjck** [einfallstoll/express-ntlm#52]
Hi Everyone.
I'm using 'express-ntlm' for my application. When the user access to my app. They need to enter username/password for authentication with LDAP.
![image](https://user-images.githubusercontent.com/18464491/34757915-4c27fd2c-f60f-11e7-99d6-ba543c6c4d85.png)
In my code, i use command: request.destroy(); or I close my browser and open this again then my app required username/passsword. 
How to they can logout without run behavior above.

**Comment by einfallstoll** [comment]
Chrome seems to be a little "special" when talking about NTLM. It seems like it actually **is** supported, but needs some [additional setup](https://sites.google.com/a/chromium.org/dev/developers/design-documents/http-authentication) by using a [new policy](https://dev.chromium.org/administrators/policy-list-3#AuthServerWhitelist).

Try the module first in Internet Explorer to make sure it is working at all.

**Comment by cazjck** [comment]
I know, I have already login to success my ldap. But i want to change the other account.
How to logout  ntlm ?
Thanks

**Comment by einfallstoll** [comment]
Logout of Windows and login as a different user. It does not make sense to logout just from the web application since your browser would login again automatically.

**Comment by cazjck** [comment]
I'm using ldap with web application.
`app.use(ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    forbidden: function(req, res, next) { 
        res.setHeader('WWW-Authenticate', 'NTLM');
        res.sendStatus(401);
    },

    domain: 'myldap.com',
    domaincontroller: 'ldap://myldap.com/',
}));`
When i access my web app, The browser required user/pass. 
Example: I login my PC by A account but i can login my web app by B account.
How to I logout B account and login by other account from my app( remove some field of request, clear cache browser ?)
Thanks

**Comment by einfallstoll** [comment]
This does not make sense. `express-ntlm` *should* automatically log in. If Chrome decides to mess around with NTLM, it's their problem. NTLM should not be logged out.
