### ISSUE TITLE
Problem with IE

### ISSUE THREAD

**Issue by joker63** [einfallstoll/express-ntlm#55]
I have a problem with Internet Explorer. I use ReactJS from the client to request a node.js, then proxy to api.
If the component is enabled, then part of the requests are not proxy correctly.
How authorizations work:

The user goes to '/'
If the JWT token is not present or it is not valid, the redirect to / domain
/ domain turns on your component, obtains data about users, makes a request in the API to get a JWT token.
3.a If the user is denied access, redirect to / login, for authorization. I enter login and password. I click the Log In button and get 400 error from the API. I do not change the data, I click on enter, response 200.

code 400 https://prnt.sc/j0ov6p
code 200 https://prnt.sc/j0ovax

There are errors in other requests.
Other browsers work fine.

**Comment by einfallstoll** [comment]
This has nothing to do with `express-ntlm`. At least I can't see any hint that points to this module.
