### ISSUE TITLE
Question on loading certificate from machine store

### ISSUE THREAD

**Issue by ryanvgates** [einfallstoll/express-ntlm#58]
How can I load a certificate from the machine store in Windows?

In the example, it shows how to read the ca from disk.

<pre>    tlsOptions: {
        //trusted certificate authorities (can be extracted from the server with openssh)
        ca: fs.readFileSync('./ca.pem'),
        //tells the tls module not to check the server's certificate (do not use in production)
        //rejectUnauthorized: false,
    }</pre>

I'd prefer to leverage a certificate already installed on the machine. Please let me know if you need any additional information.

**Comment by einfallstoll** [comment]
`tlsOptions` get passed through and the `ca` option ultimately ends in [tls.createSecureContext(options)](https://nodejs.org/api/tls.html). Therefore you can pass your certificate(s) from whatever source you want. Look out for some npm modules that can read the Certificate Store from Windows and provide compatible data.

**Comment by ryanvgates** [comment]
@einfallstoll Do you know of any that would be worth looking into(i.e. maintained, supported, reliable, etc.)?

**Comment by einfallstoll** [comment]
Sorry, I don't know any.

**Comment by ryanvgates** [comment]
@einfallstoll thank you for letting me know. I did find [win-ca](https://github.com/ukoloff/win-ca), but I'm still trying to get it to work.

**Comment by einfallstoll** [comment]
...and now you know why I wanted `express-ntlm` to "just work" without much configuration.

**Comment by ryanvgates** [comment]
It definitely just worked for doing LDAP. When I tried to do LDAPS with a custom root Certificate(not bundled with node), that's when it got interesting.
