### ISSUE TITLE
Works locally but not on Dev Server

### ISSUE THREAD

**Issue by ryanvgates** [einfallstoll/express-ntlm#59]
I'm building an API which I would like to have a subset of endpoints require NTLM authentication. I have gotten it working locally, but I can't seem to get it working on the Dev Server. It is running under a service account, but I have used my user as well without any success. I get the same 3 messages in the logs and a 500 response when I try to post to the authenticated endpoint.

<pre>
{
	"message": {
		"0": "[express-ntlm]",
		"1": "No Authorization header present"
	},
	"level": "debug",
	"timestamp": "2018-06-14T19:07:38.370Z"
}
{
	"message": {
		"0": "[express-ntlm]",
		"1": "Initiating connection to Active Directory server my.domain (domain MYDOMAIN) using base DN \"null\"."
	},
	"level": "debug",
	"timestamp": "2018-06-14T19:07:38.455Z"
}
{
	"message": {
		"0": "[express-ntlm]",
		"1": "Unexpected NTLM message Type 3 in new connection for URI http://webserver:1234/auth/"
	},
	"level": "debug",
	"timestamp": "2018-06-14T19:07:38.857Z"
}
</pre>

I'm kind of at a loss as far as what to try next for troubleshooting. Let me know if you need anything else.

**Comment by einfallstoll** [comment]
Looks like you're using a proxy on the dev server. That would be not supported by NTLM as it authenticates the connection.

**Comment by einfallstoll** [comment]
There you have your proxy. IIS might have some NTLM-related settings, but I'm not sure. It might also help to dig into Keep-Alive settings but I can't help you as the issue is NTLM-related and not related to this module.
