### ISSUE TITLE
Safari and Firefox not asking for user and password after redirection 

### ISSUE THREAD

**Issue by danielriosb** [einfallstoll/express-ntlm#63]
Hello,

I'm trying to prompt users for User and Pass again after a wrong password or username but on Safari and Firefox this code doesn't work. Browser keeps reloading after a wrong user or password has been inserted. 

```
forbidden: function(req,res){
    res
      .status(401)
      .send(`<!DOCTYPE html><html><head><body>
      <h2>Login failed, Please try again.</h2></body></head>
      <script>
      window.setTimeout(function() {
        window.location.href = '${req.url}';
      }, 1000);
      </script></html>`)
  }
```

**Comment by einfallstoll** [comment]
NTLM is not supposed to be manually entered, therefore you should maybe try to use some other authentication method (e.g. form-based authentication that will authenticate against an Active Directory by binding).

**Comment by danielriosb** [comment]
Yeah but for some reason it is manually entered when you are using Mac OS or it is happening just to me?
