### ISSUE TITLE
Get [ DomainName":"MYDOMAIN","UserName":"MYUSER","Workstation":"MYWORKSTATION ] directly? 

### ISSUE THREAD

**Issue by nbatwara** [einfallstoll/express-ntlm#65]
Is there anyway to get this info directly: DomainName":"MYDOMAIN","UserName":"MYUSER","Workstation":"MYWORKSTATION. 
So basically by passing the request as an explicit function and just retrieving that information?

**Comment by einfallstoll** [comment]
I'm not sure whether I understand your question completely. Could you make an example what you want to achieve?

**Comment by nbatwara** [comment]
Yeah sorry about that.  Also, I do understand this is more of a StackOverflow question and not an issue with the package so I really appreciate your response! 
So what I'm trying to achieve is trying to just fetch the Domain Name, Username and possibly Workstation. I don't want any explicit authentication. What's happening currently is that after express-ntlm is added to the middleware stack my other auth mechanism is blocked off and am not able to login. 

Here is a snippet of my code: 
`import express from 'express';
import bodyParser from 'body-parser';
import jsonwebtoken from 'jsonwebtoken';
import cors from 'cors';
import Config from './config';
import { authenticate, authError } from './middleware';

const { port, secretKey, expiredAfter } = Config;
const app = express();
const ntlm = require('express-ntlm');


function doesUserExists(username, password) {
	const user = {
		id: 1,
		username: 'demo@username.com',
		password: 'demo',
	};
	if (username === user.username && password === user.password) {
		return true;
	}
	return false;
}

app
	.use(bodyParser.urlencoded({ extended: true }))
	.use(bodyParser.json())
	.use(cors());

app.use(ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    domain: 'MYDOMAIN',
    domaincontroller: 'MYDOMAINCONTROLLER',

}));

app.get('/', (req, res) => {
	res.json({ status: 'OK' });
});

// app.get('/getauth', function(request, response) {
//     console.log(JSON.stringify(request.ntlm)); // {"DomainName":"MYDOMAIN","UserName":"MYUSER","Workstation":"MYWORKSTATION"}
// });

app.post('/api/login', (req, res) => {
	const { username, password } = req.body;
	const response = {};
	// You can use DB checking here

	if (doesUserExists(username, password)) {
		response.token = jsonwebtoken.sign(
			{
				expiredAt: new Date().getTime() + expiredAfter,
				username,
				id: 1,
			},
			secretKey
		);
	} else {
		response.error = 'Not found';
	}
	res.json(response);
});
app.use('/api/secret', [authenticate, authError]);
app.post('/api/secret/test', (req, res) => {
	res.json({
		status: 200,
		message: 'succcesful',
	});
});

app.listen(port, () => {
	console.log('JWT Login ' + port);
});
`

Error I get: 

> [express-ntlm] Error when parsing Authorization header for URI http://localhost:9000/api/login

**Comment by einfallstoll** [comment]
I guess you want both NTLM for convenience of the SSO in the browser and a regular easy login for your API. Right?

You can always add more logic to the middleware stack:

```
const ntlmAuth = ntlm({
    domain: "DOMAIN",
    domaincontroller: "DOMAINCONTROLLER"
});

app.use((req, res, next) => {
    if (/* user has jwt */) {
        // validate jwt
    } else if (/* user wants to access /api/login */) {
        // do login
    } else {
        ntlmAuth(req, res, next);
    }
});
```

*I just wrote this on my smartphone off my head, so it's not perfect but should give you an idea*

**Comment by nbatwara** [comment]
You're right, that's exactly what I'm looking for. I had tried something similar already but that didn't work. Here is the error I get when I implement what you mentioned up above: 

> TypeError: Cannot read property 'connection' of undefined

**Comment by einfallstoll** [comment]
This means the request is undefined, which should not be the case. Either a typo of yours, some other problem with your implementation or a logic error of myself. Can you show me how you implemented the advanced middleware handling?

**Comment by nbatwara** [comment]
I'm probably not calling it correctly, I guess. 
const ntlmAuth = ntlm({
     debug: function() {
         var args = Array.prototype.slice.apply(arguments);
         console.log.apply(null, args);
     },
    domain: 'DOMAIN',
    domaincontroller: 'MYDOMAINCONTROLLER,

});

app.post('/api/login', (req, res) => {
	const { username, password } = req.body;
	const response = {};
	**// JUST TRYING IT HERE
    ntlmAuth();**
	if (doesUserExists(username, password)) {
		response.token = jsonwebtoken.sign(
			{
				expiredAt: new Date().getTime() + expiredAfter,
				username,
				id: 1,
			},
			secretKey
		);
	} else {
		response.error = 'Not found';
	}
	res.json(response);
});

**Comment by einfallstoll** [comment]
I see the problem. `ntlm(opts)` returns a function that accepts three arguments: request, response and next. In your case the function is stored in the constant `ntlmAuth`. So you cannot call it without arguments. I really think my boilerplate will pretty much do what you want, as long as you replace my comments with actual code.
