### ISSUE TITLE
Is there a way to re-prompt for credentials?

### ISSUE THREAD

**Issue by erezhod** [einfallstoll/express-ntlm#68]
Hi guys!

I have implemented this great library in my Express project.
Some of my users will have to enter credentials manually when prompted in Chrome, but I noticed that if I get the credentials wrong for some reason (e.g: wrong password), it will not ask for ones again until I clear the website's cache, only then it will prompt for user & password once again.

Is there a way to re-prompt on unsuccessful login?

Thanks! :)

**Comment by einfallstoll** [comment]
This appears to be the same as in #63, but I didn't manage to answer it. NTLM is not designed to be a manual authentication method, so this case was never intended to happen. The question is more related on how Chrome internally handles NTLM requests (and I'm not familiar with this). But if you find let's say an HTTP status code you can send after an unsuccessful authentication which tells Chrome to not store the credentials and try it again, you can replace the default handler in the options to accomplish that.

A few thoughts on this:
- Maybe a redirection could work. However, 3XX response codes are more or less "successful"
- Maybe a 4XX response code could work, then use a `<meta>` redirect to try again

**Comment by luki1412** [comment]
You have to send 401. That's how IIS does it. Works for me. You do refresh and it asks for credentials again.

**Comment by erezhod** [comment]
Sounds great guys! Thanks, I will try these options and report back for others who might be looking or a solution.

**Comment by LukasK07** [comment]
@erezhod any updates on these options? 

> Sounds great guys! Thanks, I will try these options and report back for others who might be looking or a solution.
