### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by muhammadantoun** [einfallstoll/express-ntlm#70]
Hi Team,

Don’t you just hate it when someone includes your open source project, only to run some scanning tools and come back with issues?  Yea we do too.

So we’ve been running lots of security scans on open source projects, including yours, through some automation we built.  Don’t worry, it took less than a few minutes to run the scans and auto-generate the report.

Wasn’t sure how to send it to you, so we’ve stuck them up at https://source-security.co.uk/fd9c9d66-6f65-4113-8a72-3c7d5e8b0103/ so you can see if anything needs handled.  Feel free to re-run the security scanning anytime you like, it’s free for open source.

Best of luck,

Muhammad

**Comment by einfallstoll** [comment]
Hi @muhammadantoun,

Absolutely fair and nice to make some automated security scanning against public OSS. I'm glad there aren't any easily detectable serious vulnerabilities.

Cheers.

**Comment by einfallstoll** [comment]
@muhammadantoun btw. the finding regarding Regular Expressions is a false positive. I use it to generate a UUIDv4 off a static pattern.
