### ISSUE TITLE
How can i disable display standard auth window?

### ISSUE THREAD

**Issue by grishnyakov** [einfallstoll/express-ntlm#75]
This problen happens in "incognito" tabs
![image](https://user-images.githubusercontent.com/29563933/93590173-7e3daa00-f9c7-11ea-9b2d-c37fbde33c67.png)

**Comment by einfallstoll** [comment]
This is specific to Google Chrome / Chromium and you can't overwrite this behavior (except you maybe go into the settings of Chrome and disable NTLM or something).

If you don't like it, I'd recommend to offer NTLM only on a separate path (e.g. /auth/ntlm) and after successful authentication you create a session. For the other cases you can provide a username/password login on a separate path (e.g. /auth/plain) and create a session as well after successful authentication.
