### ISSUE TITLE
Is it possible to enable NTLM only for some routes only?

### ISSUE THREAD

**Issue by baur** [einfallstoll/express-ntlm#77]
Hi, Friend!
Is it possible to enable NTLM only for some routes only?

**Comment by einfallstoll** [comment]
Yes! You can use `express-ntlm` just like any other express middleware.

See:
- https://expressjs.com/en/guide/using-middleware.html#middleware.router
- https://stackoverflow.com/questions/12921658/use-specific-middleware-in-express-for-all-paths-except-a-specific-one

**Comment by baur** [comment]
I already tried

```
const unless = require('express-unless');
app.use(ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    domain: '.....',
    domaincontroller: 'ldap://....',
}).unless({ path: ['/users/login']}));
```
}).unless({ path: ['/users/login']}));
   ^

```
TypeError: ntlm(...).unless is not a function
    at Object.<anonymous> (e:\web\Node\Grafana-generic_OAuth-NodeJS-NTLM\server.js:20:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by einfallstoll** [comment]
Well, I don't know what `express-unless` is, this has nothing to do with `express-ntlm` and I will not add support for it. But if I read the very first example of its description, you're supposed to do something like `ntlm.unless = unless;` prior to using it.

**Comment by baur** [comment]
I'll try to enable NTLM for only one route `http://server/login`  to get the current login!
Thank you!!!

**Comment by baur** [comment]
> Yes! You can use `express-ntlm` just like any other express middleware.
> 
> See:
> 
> * https://expressjs.com/en/guide/using-middleware.html#middleware.router
> * https://stackoverflow.com/questions/12921658/use-specific-middleware-in-express-for-all-paths-except-a-specific-one

it helped me! thank you!
