### ISSUE TITLE
Is there a way to use express-ntlm as auth service?

### ISSUE THREAD

**Issue by microspace** [einfallstoll/express-ntlm#78]
I want to achieve this:
 1) use opens URL in browser
 2) if user session is not present, redirect to '/auth' URL (ntlm listerns to '/auth' URL
 3) ntlm authenticates user and redirects him to URL, opened  from browser
Problem is that  usual fetch 'auth' doesn't work here, as 
```
< HTTP/1.1 401 Unauthorized
< X-Powered-By: Express
< WWW-Authenticate: NTLM
```

is returned. So I have to reimplement ntlm negotiation steps.

**Comment by einfallstoll** [comment]
Hi, I'm sorry, but I don't understand what you mean with "usual fetch 'auth'". Can you explain it to me? Thank you!
