### ISSUE TITLE
Express-ntlm with ldaps gives  forbidden 403 error when url launched from browser

### ISSUE THREAD

**Issue by mnk-OneThing** [einfallstoll/express-ntlm#81]
Below is the code. 
When I hit the url 
http://localhost:80. I get 403 forbidden error.
I tried with openssl client to connect to ldap server its works alright I am able to connect and get the response.

What am I doing wrong here can anyone help...

```
var express = require('express'),
    ntlm = require('express-ntlm'),
    fs = require('fs');

var app = express();

app.use(ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    domain: 'eftwft',
    domaincontroller: 'ldaps://eft.wft.com.bank:636',
    tlsOptions: {    
        ca: fs.readFileSync('./eftcertifcateca.pem'),
   
    }
}));

//same as above
app.all('*', function(request, response) {
    response.end(JSON.stringify(request.ntlm)); 
});

app.listen(80);
```

**Comment by einfallstoll** [comment]
What browser do you use?

**Comment by mnk-OneThing** [comment]
I have tried chrome and edge. Problem seems to persist

**Comment by einfallstoll** [comment]
What does the debug log say? Are you sure NTLM authentication is enabled in the browser settings?

**Comment by mnk-OneThing** [comment]
Its says forbidden 403, Ntlm authentication is enabled.

**Comment by mnk-OneThing** [comment]
Its says forbidden 403, Ntlm authentication is enabled.

**Comment by einfallstoll** [comment]
Can you paste the debug output from the console here?

**Comment by mnk-OneThing** [comment]
[express-ntlm] Initiating connection to Active Directory server eft.wft.com.bank:636 <domain  eft.wft.com.bank> using base DN "null"




If issue with base DN then where should I provide the details.

**Comment by einfallstoll** [comment]
No the base DN will be ignored anyways. What else do you have as output or is this the only line?

**Comment by mnk-OneThing** [comment]
That is the only line I see in the console

**Comment by mnk-OneThing** [comment]
With the same code if I replace the 

domaincontroller: 'ldap://eft.wft.com.bank:389',

It works

**Comment by einfallstoll** [comment]
Seems like a connection issue to me. Do you have access from the server to the DC? Could it be a TLS issue?
