### ISSUE TITLE
NTLM_No_Proxy.js does not check for the type 1 unicode flag

### ISSUE THREAD

**Issue by DavidTheWin** [einfallstoll/express-ntlm#82]
`NTLM_No_Proxy.negotiate` does not check for the type 1 unicode flag when checking the request flags that were received so the client is not sent back the unicode flag in the type 2 response.

This interacts with a similar bug in the httpntlm library in it sees there is no unicode flag in the type 2 response and writes the domain/username/workstation in ascii, but then always sends the unicode flag. Then when `parse_ntlm_authenticate` parses the type 3 message, it sees the unicode flag and parses the details in unicode rather than in ascii as intended. I've raised an issue in that library to fix the contradictory type 3 message, but express-ntlm should handle the flag correctly in the first instance.

Something like the below in `NTLM_No_Proxy.negotiate` fixes the type 2 response for me, at which point both libraries interact correctly.
```javascript
...
const is_unicode = request_flags & NEGOTIATE_UNICODE;
...
if (is_unicode) {
  challenge_flags |= NEGOTIATE_UNICODE
}
```

**Comment by einfallstoll** [comment]
Would you mind to do a PR? I will happily merge and deploy it within a timely manner

**Comment by DavidTheWin** [comment]
Raised https://github.com/einfallstoll/express-ntlm/pull/83

**Comment by einfallstoll** [comment]
It's published. Thanks a lot.

**Comment by bjowes** [comment]
The PR #83 does not follow the spec - the Win32 API (and my own NTLM code) can no longer parse the Type 2 message from express-ntlm after this was introduced.

According to the specs, the client indicates which encodings it supports using the flags in the Type 1 message, using the NEGOTIATE_OEM and NEGOTIATE_UNICODE flags. 
Then it is up to the server to decide which encoding to use. This is done by returning one of the encoding flags sent by the client, and using that encoding when creating the Type 2 message. 
The current version of express-ntlm returns both encoding flags - meaning the client has no idea how to decode the message properly. Secondly, the target information field is always encoded as ascii, meaning that a client guessing for unicode will fail.

This is the reason that the code was initially written to always return only the OEM flag and always apply ascii encoding. If the unicode flag needs to be supported:
- the OEM flag should be cleared when using unicode
- the target info field should be encoded according to the selected encoding

Hope this makes sense. If so, I can provide a patch.

**Comment by einfallstoll** [comment]
@bjowes If you can patch it, that would be wonderful
