### ISSUE TITLE
Question: How to redirect to another React after get login name

### ISSUE THREAD

**Issue by baur** [einfallstoll/express-ntlm#85]
Hi,
Is it possible to redirect the user to another react app with auth data (login name, domain name, etc)?

**Comment by baur** [comment]
```
res.cookie('token', 'Your token', {
	maxAge: 60000, // Lifetime
})

return res.redirect('http://localhost:8080/') // Front-End App
```

**Comment by baur** [comment]
not works on cross domain

**Comment by einfallstoll** [comment]
This issue is not related to express-ntlm. You could use OIDC / OAuth for cross-domain authentication or use express-ntlm in the other application as well.
