### ISSUE TITLE
No Authorization header present

### ISSUE THREAD

**Issue by wiktorrudzki** [einfallstoll/express-ntlm#96]
Hi,
I am using latest version of express-ntlm - 2.7.0

I created endpoint in my application for user authentication via Active Directory without providing any credentials. This is my code so far:
![image](https://github.com/einfallstoll/express-ntlm/assets/95183973/d982b01a-6396-4cfe-a74f-025b8aa239b2)

I am logged in to Windows with Active Directory account and I am trying to authenticate user using code but instead, I get a following response:
![image](https://github.com/einfallstoll/express-ntlm/assets/95183973/9385b948-4183-4392-813c-dd46fa0948e3)

I don't know if I am supposed to set a header called `Authentication` on the client side, but if I am, I don't really know what should I save there.

Is there anyone who had a similar problem? Or anyone who has an idea of how to solve it?
Appreciate any help from you guys

**Comment by einfallstoll** [comment]
You need to set the `WWW-Authenticate` to `NTLM` when overwriting the `unauthorized` option:

````
response.setHeader('WWW-Authenticate', 'NTLM');
````

This will tell the brower it needs to initiate NTLM authentication.

**Comment by wiktorrudzki** [comment]
> You need to set the `WWW-Authenticate` to `NTLM` when overwriting the `unauthorized` option:
> 
> ```
> response.setHeader('WWW-Authenticate', 'NTLM');
> ```
> 
> This will tell the brower it needs to initiate NTLM authentication.

Wow, it seems to be working now. I didn't see that before in the lib's definition of that method. Thank you so much :)

**Comment by einfallstoll** [comment]
It's also in the README 🤫

**Comment by wiktorrudzki** [comment]
@einfallstoll can I have another question actually?

I was getting an error: `Cannot set properties of undefined (setting ntlm)` right in this line of code:
![image](https://github.com/einfallstoll/express-ntlm/assets/95183973/080242fc-9181-4ba1-97f0-5934cd68ddc9)

It was happening because `locals` in my case was undefined so I commented out this line and it seems to work since then and not break anything as well. Maybe, if you knew why was it happening, I wouldn't have to override anything.

I am using Next.js technology in this project

Thanks in advance for any response :)

**Comment by einfallstoll** [comment]
It's supposed to be used as an express middleware. But I guess you could wrap it in a function, set `response.locals = {}` then pass it to `expressNtlm(...)(request, response)`

**Comment by wiktorrudzki** [comment]
It worked, thank you so much once more :)
