### ISSUE TITLE
No Authorization header present in production

### ISSUE THREAD

**Issue by wiktorrudzki** [einfallstoll/express-ntlm#97]
Hello, here I am with the next issue

I have working ntlm authentication in development mode where the application properly authenticates me via Active Directory. In production on the other hand I cannot authorize a user. All I get in logs is:
[express-ntlm] No Authorization header present
[express-ntlm] Initiating connection to Active Directory server xxx (yyy) using base DN "null".

I assume it has nothing to do with the fact that base DN is `null` because I get the same message in development mode.
But I do not get the message about an authorization header. I have tried both cases - where I override `unauthorized` method and yes, I do set this header: `response.setHeader('WWW-Authenticate', 'NTLM')` and where I do not override anything to make sure I do not screw up things. Any ideas about what's possibly wrong?

I might add that the problem occurs in Mozilla Firefox when trying to log in with an AD account and on Google Chrome when trying to log in with a basic Windows account (which should not authenticate me but I tried it for testing purposes). Unfortunately, I am not able to test any other cases for now

I would appreciate any response from you guys

EDIT
It may have something to do with nginx which I am using to create a web server on my production machine. I am going to check it out and possibly solve it. If I fail, then I will reopen the issue

**Comment by einfallstoll** [comment]
NTLM is not compatible with reverse proxies, because they authenticate the connection will be **reused** by reverse proxies. See the README and other issues
